= Compte rendu

Mon stage a débuté le 24/02/2020 au laboratoire LAMSADE.
Cela fait en effet  trois semaines que je travaille sur le thème: Exploration expérimentale du jugement délibéré sur la décision d'établir une cantine scolaire végane.


== Semaine 1 (semaine du 24 février)

* Lecture de l'article sur le cadre formel pour le jugement délibéré.

* Création de GitHub :en effet, j'ai suivi des tutoriels pour compendre ce qu'était GitHub et comment ca fonctionnait.

** Dépot de plan

** Nom de réferenciels crées:UE 21 et Ymane 10.

** Comment créer un dossier asciidoctor.

* Sites web: essai de création de deux sites web(website et googlesites).

* Echanges avec M. CAILLOUX, nous avons fait un petit bilan de la semaine.

* Invitation de M. CAILLOUX sur GitHub comme collaborateur afin qu'il puisse suivre mon travail

* Après avoir lu l'article sur le cadre formel du jugement délibére, M. CAILLOUX M'a facilité l'accès à sa bibliothèque. Cela, afin que je puisse lire l'ouvrage de MAKISSON et ainsi, pouvoir me familiariser avec la relation de relation binaire et mieux m'imprégner des artsur la théorie de la décision et spécifiquement les cadres théoriques.


== Semaine 2 (semaine du 02 mars)

* Essai de compendre comment LaTeX et overleaf fonctionnaient.

* Lecture d'un ouvrage de MAKISSON, et quelques exercices faits sur la notion d'ensemble

* Installation de LaTeX via overleaf et essai d'un projet pour voir le fonctionnement

* Echanges avec Barnabé sur les sites web que nous avons consultés


== Semaine 3 (semaine du 9 mars)

* Littérature sur wordpress

* Echanges avec M. CAILLOUX suite à des difficultés à pouvoir écrire un résumé comparatif des sites web sous format asciidoctor

* Ajout de nouvelles taches afin de mieux cerner le fonctionnement de logiciel de traitement de texte

* Nouvelles taches

1* Suivre et faire des exercices sur l'introduction aux commandes (lien sur internet)

2* Mettre asciidoctor en local

3* Rédiger un petit texte en LaTeX en s'aidant du livre de LAMPART

== Semaine 4 (semaine du 16 mars)

* Rédaction du rapport en asciidoctor et le convertir en html et l'envoyer sur github

* Séparation du document de comptre rendu en 2 ( l'un uniquement contenant le compte rendu de mes taches et l'autre portant sur les comparaisons des sites web explorés)

* Mise à jour du README ( taches réalisées et en cours)

* Site avec wordpress (page d'accueil avec un texte introductif pour présenter l'étude et 2 vidéos)

* Début protocole (inspiré par le protocole initial)

* Discussion téléphonique avec Olivier concernant la conduite à tenir ( début du confinnement)


== Semaine 5 (semaine du 23 mars)

* Lecture de quelques lignes du livre de MAKISSON

* Réalisation d'un texte réalisé dans overleaf

* 2éme discussion avec Olivier à propos de la réconduite du stage ( hypothéses de fausses vidéos ou d'auto-filmage des experts ou simplement mettre en place un modéle qui marche bien et sur lequel d'autres stages ou recherches pourront s'appuyer)

== Semaine 6 (semaine du 30mars)

* Envoi du lien vers mon document écrit dans overleaf

* Discussion avec Olivier concernant des nouvelles taches à faire ( inclure futur et changer l'ordre : futur/réalisé/ en cours)

* Essaie mais echec pour pouvoir déployer mon site wordpress sur github (vu que je travail en local , cette tache n'est pas simple), alors Olivier s'est proposé de voir comment cela pourrait se faire

* Fin élaboration du protocole et envoi sur GitHub


== Semaine 7 (semaine du 06 avril)

* Discussions avec Barnabé concernant le site web

* Nouveau essai: Installation d'une nouvelle extentention (WP2static) dans Wordpress afin de deployer mon site sur GitHub et le rendre accéssible par Olivier

* Reprise en gras de mes propositions dans le protocole envoyé (pour faciliter la discussion avec Olivier)

* Elaboration d'un brouillon (questionnement sur l'état de l'art du stage) afin de mieux comprendre ce qui tourne autour de la théorie de la décision

== Semaine 8 (semaine du 13 avril)

* Création d'un nouveau site web (pour essayer de la déployer de nouveau et aussi pour donner une forme améliorée de ce que le sit web final ressemblerait): menu composé de 4 composantes ( experts, arguments, formulaire et accueil)

* Discussions avec Barnabé pour essayer de résoudre le probléme de déployement qui continu de se poser

* Envoi du protocole à Olivier

* Partage du brouillon sur l'état de l'art à Olivier qui m'a proposé un livre: Bouyssou, Marchant, Pirlot, Perny, Tsoukiàs, Vincke - Evaluation and Decision Models: a critical perspective (2000)

== Semaine 9 (semaine du 20 avril)

* Lecture de quelques pages du livre Evaluation and Decision Models: a critical perspective (2000) de Bouyssou, Marchant, Pirlot, Perny, Tsoukiàs, Vincke.

* Essai de nouveau de déployer le site web sur Github en changeant et créant de nouveaux réferenciels mais echéc

* Exploration de deux pistes pour deployer mon site web (Wordpress.com et Byet.host) qui sont de bonnes pistes qui marchent sauf qu'il falait recommencer un autre site

* Partage d'écran avec Barnabé et https://yasmine07.github.io/cantine-vegane/[site web déployé sur GitHub]

== Semaine 10 (semaine du 27 Avril)

* Réunion visiconférence avec mes trois encadrants de stage : avec Olivier, nous avons fait le points aux autres à Nicolas et Yves et nous nos sommes donné un objectif à ourt terme d'une durée de une semaine (faire une liste potentielle d'experts)

* Contact de diététiciens (8 dont 5 m'ont fait un retour)

* Contact d'associations ( végétariens/ environnement/ bien-etre animal) : Greenpeace, L214, Association des végétariens de France, Végécantines et Vegan-pratique (site gére par l'association des végétariens de France), L214 Ethique et animaux (facebook)

* Vegan-pratique; retour et fournit des pistes de contact pour experts potentiels

* Mail envoyé au Pr https://www.avenue-centrale.fr/Laurent_Begue[BEGUE] et retour (deux noms d'experts)

* Mail envoyé à http://www.alimentation-responsable.com/qui-sommes-nous[l'APSARes]

* Consultation de https://www.reponsearmb.com[la liste de médecins ayant répondu en 2019 à l’ARMB ]au sujet des alimentations 

* https://github.com/Yasmine07/D-lib-jugdment/blob/master/Liste.adoc[Liste d'experts potentiels]

== Semaine 11 (semaine du 04 mai)

* Réunion par visioconférence avec mes trois encandrants:

** Trouver d'abord des experts avec un penchant contre la cantine végane (car plus dur à trouver

** Ecrire au proffesseure MARGARITIS pour avoir une idée claire de sa position

** Discuter sur le protocole: fournit à l'expert lorsque celui-ci le réclame

** Discuter sur la facon d'approcher le professeure

* Mail envoyé au professeure

** Le professeure au vu de sa position à l'ANSES ne peut emettre des arguments "contre" la cantine végane

** Ne connait pas de personnes qui soient fondammentalement "contre" la cantine végane

* Recherches sur internet:

** trouver un excellent profil qui serrait un expert avec des arguments plutot tournés contre la cantine végane : monsieur DUMAS Jean-Francois

** Recherche pendants des jours de son adresse mail (sans succès)

*** pagesjaunes;pagesblanches

*** son https://www.jfdumas.fr/[blog]; https://www.fontenay-aux-roses.fr/[le site web de la mairie] dans laquelle il était maire adjoint; 

*** https://twitter.com/dumas_jf[twitter], facebook, https://www.youtube.com/watch?v=x6wxbOvGDCE&t=184s[youtube], des forums de végétariens ou ses articles sont souvent contre-argumentés: tout cela sans succès jusqu'à présent

* Continue la recherche parallélement pour avoir un autre expert qui serait aussi interessant

== Semaine 12 (semaine du 11 mai)

** Mail adressé à un chercheur avec de grands centres d'interets autour des plats végétalisés (recommendé par mon professeur d'école) pour avoir des pistes vers des personnalités qui auraients des arguments contre la cantine végane : pas de suite favorable ( intéressé mais pas de disponibilité)

* Lecture du quelques pages du livre sur https://www.macmillanihe.com/resources/sample-chapters/9780230252165_sample.pdf[la démocratie délibérative de Chappell que Yves m'a envoyé]

* Réunion avec mes encadrants

** Discussion du retour du professeur BEGUE: qui propose de construire soi meme les aguments et les distribuer aux experts que l'on choisire et aussi tenir compte du contenu des arguments et l'éloquence de la personne (cela pourrait constituer un biais)

** Travailler sur une liste de critères pour la sélection des champions

** Valider notre expert ''pour'' et trouver notre expert ''contre''

** Nom d'un champion ''contre'' fournit par Nicolas ( Paul ARIES)

== Semaine 13 (semaine du 18 mai)

* https://github.com/Yasmine07/D-lib-jugdment/blob/master/Crit%C3%A8res%20de%20s%C3%A9lection.adoc[Liste de critéres pour experts]

* Contact de plusieurs personnalités 

** Madame https://jocelyneporcher.fr/[Jocelyne PORCHER] pour arhumentaire contre

** Monsieur http://paularies.canalblog.com/[Paul ARIES] pour argumentaire contre

** Monsieur http://www.fredericdenhez.fr/[Fréderic DENHEZ] pour argument contre: reponse favorable (cependant pour une cantine végétarienne et non végane)

** Monsieur https://eren.univ-paris13.fr/images/images/stories/CV/CV-CHAPELOT.pdf[Didier CHAPELOT] pour argumentaire pour : interessé mais peur que les vidéos ternissent son image car pourrait circulées décontextualiées

** Madame https://fr.wikipedia.org/wiki/%C3%89lodie_Vieille_Blanchard[Elodie VIEILLE BLANCHARD] pour argumentaire pour : intéressée et accord favorable

** Pas de contact avec monsieur Jean-Francois DUMAS : la mairie n'a pa ou ne peut donner contact (n'y travaillant plus et n'y résidant plus)

* Réunon avec mes encadrants

** Trouver des indicateurs afin de légitimer mes critéres de sélection

** Réflexions concernant le protocole: Regrouper les hypothèses en deux groupes

*** Questionnements en suspend: pour l' appréciation des champions

*** Questionnements à trancher

*** https://github.com/Yasmine07/D-lib-jugdment/blob/master/Protocole.adoc[Lien vers les suggestions] sur le protocole initial ( les phrases en gras sont mes suggestions)

** Formaliser l'accord avec les champions

*** Pour le mode de récolte des vidéos, montage éventuel

*** Le matériel à utiliser

*** Le temps imparti pour répondre aux arguments de l'autre expert, la durée d'une séquence de vidéo et autres aspects s'ils souhaitent les intégrer  

** Discussion concernant le dispositif actuel de l'étude: alternative végane versus végétarienne

== Semaine 14 ( semaine du 25 avril)

* Echanges avec Mme PORCHER 

** Motivations: qu'est ce qui a prévalu au choix de la thématique cantine végane?

**  Présentations de mes encadrants et moi et de nos motivations pour la thématique

* Echanges avec monsieur DENHEZ

** Matériel dont il posséde pour la récolte de vidéos: 5D MK2 (camére) et d'un micro professionnel

** Il enverra les fichiers bruts et on en fera ce que l'on veut avec

** Choix face caméra souhaitée ?

* Echanges avec madame VIEILLE BLANCHARD

** Précision de la position à argumenter: option chaque jour et un jour imposé, qui revient au choix 3: lundi végan

** Compte utiliser la caméra de son ordinateur

* Réunion avec les encandrants

** Compte rendu sur les échanges avec les experts

** Mme PORCHER ayant aussi acceptée de participer au dispositif, nous en avons discuté et décidé de lui présenter nos excuses (car monsieur DENHEZ a repondu avant elle et qu'il est très motivé pour mener l'expérience).

** Pour les critéres pour la selecton des experts, il ressort que Mme PORCHER rempli plus de critéres que M. DENHEZ
( Plus comparable à Mme VIEILLE BLANCHARD)

** Olivier et moi réfléchirons au protocole pour la semaine prochaine

** Mieux le peaufiner






 
 






