= Compte rendu

Mon stage a débuté le 24/02/2020 au laboratoire LAMSADE.
Cela fait en effat trois semaines que je travaille sur le thème: Exploration expérimentale du jugement délibéré sur la décision d'établir une cantine scolaire végane.
Le plan suivant fut adopté en commun accord avec Olivier CAILLOUX mon maitre de stage.

 Plan
* Dépot sur GitHub
* Site web: vidéos
* Réflexions concernant le protocole
* Réflexions sur le choix des champions
* Discussions avec Nicolas concernant le choix des champions, le protocole et le montage  des vidéos
* Littérature concernant la délibération


Semaine 1::

* Lecture de l'article sur le cadre formel pour le jugement délibéré.

* Création de GitHub.

En effet, j'ai suivi des tutoriels pour compendre ce qu'était GitHub et comment ca fonctionnait.

** Dépot de plan

** Nom de réferenciels crées:UE 21 et Ymane 10.

** Comment créer un dossier asciidoctor.

* Sites web: essai de création de deux sites web(website et googlesites).

* Echanges avec M. CAILLOUX, nous avons fait un petit bilan de la semaine.

* Invitation de M. CAILLOUX sur GitHub comme collaborateur afin qu'il puisse suivre mon travail

* Après avoir lu l'article sur le cadre formel du jugement délibére, M. CAILLOUX M'a facilité l'accès à sa bibliothèque. Cela, afin que je puisse lire l'ouvrage de MAKISSON et ainsi, pouvoir me familiariser avec la relation de relation binaire et mieux m'imprégner des artsur la théorie de la décision et spécifiquement les cadres théoriques.


= Semaine 2::

* Essai de compendre comment LaTeX et overleaf fonctionnaient.

* Lecture d'un ouvrage de MAKISSON, et quelques exercices faits sur la notion d'ensemble

* Installation de LaTeX via overleaf et essai d'un projet pour voir le fonctionnement

* Echanges avec Barnabé sur les sites web que nous avons consultés


= Semaine 3::

* Littérature sur wordpress

* Echanges avec M. CAILLOUX suite à des difficultés à pouvoir écrire un résumé comparatif des sites web sous format asciidoctor

* Ajout de nouvelles tachesafin de mieux cerner le fonctionnement de logiciel de traitement de texte

Nouvelles taches::
1* Suivre et faire des exercices sur l'introduction aux commandes (lien sur internet)
2* Mettre asciidoctor en local
3* Rédiger un petit texte en LaTeX en s'aidant du livre de LAMPART






