= Démarche site web

* Installation de wordpress  https://fr.wordpress.org/download/[ici]

* Téléchargement de  xammp grâce à https://www.apachefriends.org/fr/index.html[ce lien] 

* Début de site

Wordpress étant installé en local, afin de rendre mon site accéssible par des persoonnes, il faut impérativement le mettre en ligne. En ce qui me concerne, j'ai utilisé github pour deployer un site statique et le rendre consultable.

== Avec WP2Statics

* Téléchargement et installation de l'extention WP2Statics sur WordPress

* J'ai mis en marche l'extention:

** Destination URL: j'ai mis le lien de la page GitHub (https://yasmine07.github.io/cantine-vegane/) sur laquelle je souhaite déployer mon site WordPress  

** Target directory: laisser la valeur par défaut (à peu près C:\xampp\htdocs\wordpress\mystaticsite) 

** Et pour finir j'ai lancé l’exportation !

* Il faut ensuite initialiser le dépôt dans le répertoire mystaticsite une fois l'exportation effectué (git init et git remote add origin https://github.com/Yasmine07/cantine-vegane.git 

* Sur l’appli GitHub Desktop faire File -> Add Local Repository (ou ctrl+o) et mettre le chemin de mystaticsite. On peut ensuite voir les fichiers exportés par l'extension dans GitHub Desktop. On fait un commit puis un push. Les fichiers sont dans le dépôt GitHub https://github.com/Yasmine07/cantine-vegane. GitHub génère automatiquement le site statique.

* Pour les changements il suffit de faire ces manipulations sans initialiser le dépôt git.

== Avec Simply static (ne fonctionne pas)

Simpy static est une extention que j'ai d'abord installée afin de pouvoir déployer le site sur GitHub.

* Création d'un référentiel de pages Github pour héberger le site WordPress statique

* Création d'un ensemble de branches gh-pages par défaut et suppression de la branche principale

* Cloner le référentiel GitHub sur ma machine en locale (github desktop)

* Création  d'un site statique à partir de WordPress (  j'ai mis à jour les paramètres Simply Static )

* Génerer du contenu statique : j'ai cliqué sur «Générer des fichiers statiques»

* Retour sur Pages GitHub pour vérifier mon référentiel: je constate que le dépot a été effectué ( normalement je ne saurais le dire)

* Site web initial déployé sur github https://yasmine07.github.io/cantine-vegane/[fond mais pas la forme]
