= Protocole d'étude 

== Exploration expérimentale du jugement délibére sur la décision d'établir une cantine scolaire végane
=== Justification de l'étude

La théorie de la décision se concentre sur les notions de croyances et de préférences. Ici, nous voulons
explorer le rôle trop négligé que l’argumentation peut jouer dans l’aide à la décision. A ce sujet, un cadre théorique (Cailloux et Meinard 2018) d’exploration du jugement délibéré d’un
individu soumis à un choix. Nous voulons utiliser ce cadre théorique sur le cas d’étude de
l’établissement (ou non) d’une cantine scolaire végane en France. *Le régime alimentaire global est un déterminant principal de la survenue de maladies dites chroniques.Ce thème participe de
questionnements sociétaux actuels sur la place des plats plus végétalisés car les régimes végétariens ont été associés avec un risque plus faible de diabètes, de cancers et de maladies cardiovasculaires dans les études prospectives.*

== Méthodologie
=== Type d'étude

*Notre étude est de type expérimental. Le dispositif expérimental
implique de soumettre un grand nombre d’individus aux arguments de deux experts opposés sur cette
question via des vidéos publiées en ligne et présentant leurs arguments et les contre-arguments qu’ils
opposent à leur adversaire.*

=== Objectifs

L’objectif de ce dispositif est double, à la fois de réaliser une expérience
susceptible de révéler à l’individu testé son jugement délibéré sur la question et, de l’autre, de
mesurer l’effet de changement de son opinion par le passage par une telle expérience. 

== Protocole
Supposons que nous ayons deux experts, Ca et Cb.

=== Phase de collecte

Nous demandons à Ca et Cb leurs propositions favorites, définies respectivement comme ta et tb (à choisir parmi les items 1 à 4 comme défini dans la section 1). Avec un peu de chance, nous avons choisi Ca et Cb pour que ta et tb soient aux extrémités opposées du spectre. Nous demandons à Ca de produire une vidéo en faveur de ta, et de l'étiqueter s1a. Nous envoyons s1a à Ca. Nous donnons à Cb un choix: soit produire une vidéo de réponse (en argumentant pour tb contre la vidéo en argumentant pour ta), soit démarrer un nouveau thread en faveur de tb. Dans le premier cas, nous étiquetons l'argument s1ab. Dans le second cas, nous étiquetons l'argument s1b. Nous répétons ce schéma ad nauseam. Nous exécutons également un schéma parallèle commençant par b au lieu de a. Voici une description plus précise de la phase de collecte.

• Au début de toute la procédure, les deux champions sont pleinement informés de la procédure et de l'utilisation future de leurs arguments, y compris des contraintes de temps (en fait, comme s'ils avaient reçu une copie de l'ensemble de ce document, sauf éventuellement sous une forme différente plus approprié pour une compréhension facile de leur rôle).
 
• Le schéma de dénomination est tel que la dernière lettre d'une vidéo indique son auteur.
 
• Définissez init (α), avec α ∈ {a, b}, comme suit. Condition préalable: Cα n'a reçu aucun argument d'aucune sorte de la part de son adversaire. Nous demandons à Cα de produire une vidéo en faveur de tα et étiquetons la vidéo résultante s1α. 

• Définissez next (α), avec α ∈  {a, b}, comme étant le plus grand numéro numéroté d'une vidéo de démarrage enregistrée par α dans l'ensemble du processus jusqu'à présent. Par exemple, si α = b, et si une vidéo étiquetée s3b existe déjà mais qu'aucune vidéo étiquetée s4b n'existe encore, alors le suivant (b) = 4. 

• Définissez reply (S), avec S un ensemble de vidéos précédemment produites par un expert donné α, comme suit. Nous nous adressons à l'expert β, avec β ̸ = α. Nous lui envoyons les vidéos en S. Environ une semaine plus tard, nous le rencontrons, et nous lui laissons répondre à toutes les vidéos auxquelles il veut répondre en enregistrant de nouvelles vidéos.

Une vidéo répondant à une autre vidéo est étiquetée en suffixant β au libellé de la vidéo à laquelle elle répond. Par exemple, si α = a, lors de la réponse à une vidéo intitulée s1aba, nous la nommons s1abab. L'ensemble des réponses peut être vide. Elle peut également démarrer une nouvelle vidéo qui n'est pas une réponse, que nous nommons skβ, avec k égal à suivant (β). 

• Nous commençons par init (a) et init (b) en parallèle, obtenant ainsi s1a et s1b. Définissez S1a = {s1a} et S1b = {s1b}. 

• Après avoir obtenu un ensemble de vidéos S, si S ̸ = ∅, nous exécutons la réponse (S), et étiquetons l'ensemble des vidéos résultantes en suffixant l'identifiant de leur auteur sur l'étiquette de S.
 
• Nous répétons l'étape précédente, exécuter deux threads en parallèle chaque fois que possible, jusqu'à épuisement des deux participants. 

• Lorsque les deux participants ont fini de produire des vidéos, nous leur demandons d'étiqueter brièvement (max. X mots, à déterminer)*(deux premieres lettres du nom de chaque expert)* chacune de leurs propres vidéos et de sélectionner une image de la vidéo qui deviendra sa «vignette». 

Exemple 1 Voici un exemple d'exécution. 

1. Définissez Sa = {s1a} et Sb = {s1b}. 

2. Nous appliquons la réponse ({s1a}) et obtenons Sab = {s1ab, s2b}. 

3. En parallèle, nous appliquons la réponse ({s1b}) et obtenons Sba = {s1ba}. 

4. Nous appliquons la réponse (Sab) (dès que Sab est disponible) et obtenons Saba = {s1aba, s2ba, s2a}. 

5. Nous appliquons la réponse (Sba) (dès que Sba est disponible), mais Cb ne voit pas la nécessité de répondre à ces arguments ridicules; on obtient Sbab = ∅.

6. Nous appliquons la réponse (Saba) (dès que Saba est disponible), où Cb voit une opportunité de répondre; on obtient Sabab = {s2bab}. 

7. On applique la réponse (Sabab) (dès que l'argument est disponible), Ca en a vraiment marre de tout ce cirque, et on obtient Sababa = ∅. 

Nous mettons chaque vidéo collectée sur un site Web et nous concevons tout pour que la deuxième phase du protocole (voir ci-dessous) puisse être exécutée.

=== Arbitrage

Lorsque la phase de collecte est terminée, nous entamons la phase d'arbitrage. Un individu i vient sur notre site web. L'individu i est informé par un texte introductif que son opinion délibéré est demandé. Aussi, il lui sera expliqué, que deux personnalités publiques bien connues ont plaidées pour deux options, et enfin le contexte et les choix possibles lui seront présentés. L'individu i est alors invité à passer autant de temps qu'il souhaite regarder des vidéos (sans restriction d'équilibrer le temps passé pour chaque champion) pour former une opinion. Il doit s'inscrire, en utilisant une adresse e-mail, avant de pouvoir commencer à visionner les vidéos. 

* La phase est composé d'étapes. Chaque étape commence par un ensemble associé de vidéos «proposées», Sp, et une liste associée de vidéos «vues», Ss. La liste Ss est éventuellement augmentée à la fin de chaque étape tandis que l'ensemble Sp est calculé au début de chaque étape à partir de la liste SS issue de l'étape précédente

* Au début, Ss = ∅

* Une «étape» consiste à montrer l'ensemble Sp parmi lequel l'individu peut choisir la vidéo qu'il va regarder pendant cette étape; et il peut également regarder à nouveau des vidéos qui sont «vues». Chaque vidéo est affichée sous forme de miniature, avec son étiquette clairement affichée, dans un ordre aléatoire; les vidéos de Ss sont clairement distinguées et affichées ensuite, dans l'ordre dans lequel elles sont entrées dans la liste (l'ordre dans lequel elles ont été marquées comme «vues»). i clique sur une vidéo et commence à la regarder. Il peut naviguer dans la chronologie de la vidéo (à la youtube). L'étape est terminée avec l'une de ces possibilités

** Si la vidéo est regardée jusqu'à la fin sans navigation dans la chronologie, auquel cas la vidéo est ajoutée à la fin de Ss
 
** L'utilisateur peut également cliquer pour marquer la vidéo comme vue sans l'avoir entièrement regardée, auquel cas la vidéo est également ajoutée à la fin de Ss

** L'utilisateur peut également cliquer pour arrêter la vidéo sans la marquer comme vue; auquel cas Ss n'est pas modifié et la vidéo est ajoutée à la fin de Sp

* Étant donné une vidéo s, définissez r (s) comme l'ensemble singleton contenant la vidéo de réponse à s (ainsi produite par l'autre expert que l'auteur de s), si une telle vidéo existe, et ∅ sinon. Par exemple, r (s2aba) = {s2abab} si une telle vidéo existe.

Au début d'une étape où la liste des vidéos vu est Ss∈SS, Sp est défini comme les vidéos non vues parmi les vidéos de départ et les vidéos répondant à une vidéo qui a été vue, donc, Sp = {skα, k ∈N, α ∈ {a, b}} ∪ Ss∈SS r (s) \ SS

• À tout moment (sauf en regardant une vidéo en plein écran), i voit combien de temps il a passé à regarder des vidéos de chaque expert. (Pour le pousser doucement à équilibrer son temps de vision entre les deux champions.) 

• Si i interrompt et revient plus tard, il doit se reconnecter et il recommence à l'étape où i était lorsque nous avons perdu sa trace. À chaque étape, i peut cliquer sur «questionnaire» pour accéder à la partie questionnaire. Dans cette partie, il est informé que nous suggérons de ne répondre à ces questions qu'après avoir formulé une opinion délibérée, mais qu'il peut de toute façon revenir à la partie vidéo et revenir au questionnaire quand il le souhaite et changer ses réponses. Le questionnaire pose les questions suivantes. 

• Quel est votre choix de réponse? 

• Quelle réponse auriez-vous choisie si la question avait été posée avant de voir les vidéos? 

• Quelles vidéos sont les plus convaincantes pour vous (sélection des vidéos des deux experts possible)? 

• Quelles vidéos avez-vous trouvées les plus instructives de l'expert a? De l'expert b?
 
• Quelles vidéos sélectionneriez-vous pour les montrer aux autres utilisateurs afin de les aider à se forger un jugement délibéré sur cette question?

• Considérez-vous que c'est votre réponse finale à la question, ou considérez-vous probable (possible?) Que vous changeriez encore d'avis si vous regardiez plus de vidéos? 

• Avez-vous utilisé d'autres sources que les vidéos de ce site web pour vous prononcer sur cette question après avoir entendu cette question (en vous référant à la section 1)? Pour chacune des questions «quelles vidéos», il affiche la liste des vignettes des vidéos en Ss, suivies des vignettes des vidéos qu'il a partiellement vues (mais pas marquées comme vues), et peut vérifier n'importe quelle vignette qu'il souhaite.

Nous devrions déjà penser à certaines des analyses que nous voudrons faire, afin de nous assurer que notre phase de collecte est appropriée et de documenter la programmation de la phase d'arbitrage. Nous comptons le temps vraiment passé à lire une vidéo, y compris les rediffusions lorsque i regarde plusieurs fois la même (partie d'une vidéo, et donc sans compter entièrement une vidéo qui a été partiellement visionnée, même si la vidéo a été incluse dans Ss en raison d'une demande explicite de i. Cela permet de compter le temps alloué à chaque expert.

=== Plus

*1. Nous pourrions demander aux experts à la fin du filmage, de supprimer ou promouvoir des vidéos (Ils pourraient penser que certaines de leurs vidéos sont bien meilleures que d'autres.)*

2. Nous nous assurons que nous ne proposerons les vidéos «réponses» qu'une fois qu'il aura marqué la vidéo comme «vue».
 
3. L'utilisateur affiche la question à tout moment et est invité à donner son jugement actuel sur la meilleure réponse, et peut changer sa réponse après chaque vidéo si il le souhaite. Quelque chose comme: "quel serait votre jugement actuel sur la meilleure réponse à cette question à ce stade?" 
*Cela est un peu lourd pour l'utilisateur. On pourrait s'assurer que il ne réponde à cela que lorsque qu'il veut quitter le site (comme une question imposée)
A chaque fois que i regarde une vidéo et son contre argument, lui afficher une question sur son choix de réponse actuel. Et après avoir visionner une vidéo, si la personne veut quitter le site le proposer de regarder le contre argument avant de partir, ou sinon l'afficher une question demandant de donner son choix.*

4. Nous devons introduire quelques suggestions aléatoires: *certaines personnes sont dirigées (plus ou moins contraignantes) vers des vidéos, afin de pouvoir analyser le résultat sur le DJ en fonction du chemin d'entré*

*Pour avoir une conclusion solide sur la stabilité de la réponse, nous allons diriger des personnes (une sorte de contrainte) vers des chemins de réponses bien spécifiques. Enfin, il sera réalisé un premier test de validation du dispositif
sur un premier échantillon d’individus afin de calibrer au mieux l’expérience. Cette première analyse permettra
de finaliser le protocole pour l’appliquer à un plus large échantillon.*

=== Alternative

*Vu la situation de pandémie du COVID-19, aller filmer des experts s'annonce difficile.
On présagerait alors, dès que notre site web est prêt, de mettre de fausses vidéos et à partir de là, expérimenter notre théorie , en s'assurant que le cadre marche bien sinon, nous releverons les failles pour une amélioration ultérieure.
Soit, nous pourrions demander aux experts, de se filmer et nous envoyer alors leurs vidéos. Et ainsi, ces vidéos seront mis sur le site et le protocole initial sera suivi sans changement.*

=== Analyse

*Après avoir collecté les vidéos, reçu la participation des utilisateurs sur le site et recolté leurs opinions, nous pourrions chercher des corrérations entre le jugement délibéré et certaines variables (temps de visionage, nombre de fois passer à vissionner la vidéos, temps alloué à chaque expert, stabilité de la réponse).
a travers un logiciel (SAS ou R...).*
