=  Activités du stage

== Plan
- dépôt sur GitHub, création d’un fichier asciidoctor avec le plan
- Site web : vidéos ; … (asciidoctor)
- LaTeX ou Overleaf
- Réflexions concernant le protocole
- Réflexions concernant le choix des champions
- Discussion avec Nicolas concernant le choix des champions, le protocole et le montage vidéo
- Littérature concernant la délibération (Fishkin & cie)
- Mettre asciidoctor en local
- Introduction aux commandes

== Réalisés
Website.fr

Points faibles

De nombreuses options payantes mais pas toutes (formulaire par exemple est payante et pourtant capital dans notre travail de site).

Points forts

Nombre important de thèmes environ 200 (prédéfini)

Facilité de manipulabilité

Possibilité d’ajouter des vidéos

Un formulaire prédéfini avec possibilité de personnalisation cependant, il faut payer pour la modification

Googlesites

Points Forts

Présence de zone dédiée à la saisie des mails des personnes dont on vodrait qu’ils visionner notre site, ou si on décide de le rendre public.

 -  Overleaf(https://fr.overleaf.com/read/hdrqjpvqmbwy)
- Mettre asciidoctor en local
- Introduction aux commandes

== En cours
-  Site web (http://localhost/alimentation/wordpress/wp-admin/post.php?post=22&action=elementor)
- Réflexions concernant le protocole
- Choix des champions
