= Résumé des references concernant le jugement délibéré

== Stumbling on happiness

* Note 42 à 45: Les gens ne voient que ce qu'ils veulent voir, en ce sens qu'ils ne portent de crédit qu'aux choses ou arguments qui vont dans leur champs de pensée.

* Exemple: lorsque les pro-israéliens et les pro-arabes regardent la couverutre médiatique leur concernat: chacun d'eux se dit étre ceux qui sont opprimés.
Aussi, lorsque républicains er démocrates suivent des débats sur la présidentielle, chacun voient en son candidat, la personne idéale pour diriger le pays (en dépit des arguments qu'ils avancent).

* Note 46 à 47: Toute personne place son niveau de confiance (preuve) entre deux extremes (une qui stipulerait que rien ne peut etre prouvé et l'autre, son opposé qui accepterait tout ans aucune execption comme véracité).
Et c'est en fonction du niveau ou chacun place son curseur que on accepte reconnaitre ou pas des situations comme véridictes.

* Exemple: Dans une étude, on demande si l'on est pour ou contre la peine capitale aux USA. On demande ainsi, à des bénévoles de statuer sur le taux de délinquance intra états (avant et après l'instauration de la peine), et inter états (entre les états qui ne la pratique pas et ceux qui la pratique).
Ceux qui trouvent la peine capitale comme étant néfaste soulevent des arguments qui remettent en cause la comparabilité (temporalité, le niveau de chomage et le niveau de revenus de la population)? et de ce fait abaissent ou élevent la bare ou le niveau de preuve.

* Conclusion: Toute personne  soutient fermement sa position preferée malgré les preuves ou arguments dont on dispose (on tendra à les minimiser) et vice-versa pour ceux du coté opposé.


===  Deliberative Politics in Action: Analyzing Parliamentary Discourse

* Page 24: Dans le but idéal de politique deliberative, ce qui compte c'est la qualié des arguments. Les acteurs sont prets à se laisser convaincre par de mailleurs arguments selon Keohane (2001).

* Page 34: Limite de la délibération [biais de sélection]:seules les personnes ayant accés au processus délibératif sont entendu. La couche fragile de la population ne pouvant participer au processus.
Exemple; la télévision, la radio sont des moyens de déliberation opportuns et il faut de l'argent pour avoir accès à un temps d'antenne.

* Page 43: La délibération a des avantages cogitifs pour les participants, comme réduisant les jugements erronés liés à la question de politique en question.

* Page 45: La déliberation politique invitent les points de vue des autres et espérent que de nouvelles solutions apparaitront et que l'appentissage se fera. Ils apprennent donc ils seront à meme de choisir en ne considérant que la seule force de l'argument.

* Page 47: Un indicateur nécessaire: la qualité de la délibération (nous pourions ainsi, à travers nos questionnaires, demander aux utilisateurs quels aguments ils jugent de bonne qualité).

* La délibération publique requiet: patience, humilité, confiance en soi et aux autres, le respect de ceux dont les idées sont différentes, la suppression de l'interet personnelpour le bien commun.
Cependant, le respect des arguments des autres est idéalement mentionné et on a pas décrit comment il doit étre fait. 

* Page 49: la déliberation joue un grand role dans l'atteinte d'un but.
La force argumentaire permet de prendre une décision éclairée. Exemple de la guerre froide.
