= Résumé des references concernant le jugement délibéré

== Stumbling on happiness

* Note 42 à 45: Les gens ne voient que ce qu'ils veulent voir, en ce sens qu'ils ne portent de crédit qu'aux choses ou arguments qui vont dans leur champs de pensée.

* Exemple: lorsque les pro-israéliens et les pro-arabes regardent la couverutre médiatique leur concernat: chacun d'eux se dit étre ceux qui sont opprimés.
Aussi, lorsque républicains er démocrates suivent des débats sur la présidentielle, chacun voient en son candidat, la personne idéale pour diriger le pays (en dépit des arguments qu'ils avancent).

* Note 46 à 47: Toute personne place son niveau de confiance (preuve) entre deux extremes (une qui stipulerait que rien ne peut etre prouvé et l'autre, son opposé qui accepterait tout ans aucune execption comme véracité).
Et c'est en fonction du niveau ou chacun place son curseur que on accepte reconnaitre ou pas des situations comme véridictes.

* Exemple: Dans une étude, on demande si l'on est pour ou contre la peine capitale aux USA. On demande ainsi, à des bénévoles de statuer sur le taux de délinquance intra états (avant et après l'instauration de la peine), et inter états (entre les états qui ne la pratique pas et ceux qui la pratique).
Ceux qui trouvent la peine capitale comme étant néfaste soulevent des arguments qui remettent en cause la comparabilité (temporalité, le niveau de chomage et le niveau de revenus de la population)? et de ce fait abaissent ou élevent la bare ou le niveau de preuve.

* Conclusion: Toute personne  soutient fermement sa position preferée malgré les preuves ou arguments dont on dispose (on tendra à les minimiser) et vice-versa pour ceux du coté opposé.


===  Deliberative Politics in Action: Analyzing Parliamentary Discourse

* Page 24: Dans le but idéal de politique deliberative, ce qui compte c'est la qualié des arguments. Les acteurs sont prets à se laisser convaincre par de mailleurs arguments selon Keohane (2001).

* Page 34: Limite de la délibération [biais de sélection]:seules les personnes ayant accés au processus délibératif sont entendu. La couche fragile de la population ne pouvant participer au processus.
Exemple; la télévision, la radio sont des moyens de déliberation opportuns et il faut de l'argent pour avoir accès à un temps d'antenne.

* Page 43: " Lascher présente également des hypothèses sur les conséquences possibles de la dedélibération:
Selon lui, «la délibération accroît la légitimité de la décisions des juges »ou« la délibération a des avantages cognitifs pour les participants,comme réduisant les jugements erronés liés à la question de politique en question. »Faisant allusion à des tests empiriques ultérieurs de ses hypothèses, Lascher prévient que «lele travail requis ne sera pas facile. »


* Page 45: La déliberation politique invitent les points de vue des autres et espérent que de nouvelles solutions apparaitront et que l'appentissage se fera. Ils apprennent donc ils seront à meme de choisir en ne considérant que la seule force de l'argument.

* Page 47: Un indicateur nécessaire: la qualité de la délibération (nous pourions ainsi, à travers nos questionnaires, demander aux utilisateurs quels aguments ils jugent de bonne qualité).

* La délibération publique requiet: patience, humilité, confiance en soi et aux autres, le respect de ceux dont les idées sont différentes, la suppression de l'interet personnelpour le bien commun.
Cependant, le respect des arguments des autres est idéalement mentionné et on a pas décrit comment il doit étre fait. 

* Note de page 1: Une autre étude sur l'influence de la parole, voir Pelletier et al. (1999 ). Des conférences sur les systèmes alimentaires locaux dans six comtés ruraux du nord de l'État de New York furent organisés.
En comparant les points de vue avant et après ces conférences, on a constaté des changements importants,en particulier «une réflexion plus approfondie sur les questions publiques. . . semblable à ce que Dahl aappelé compréhension éclairée »(p. 121).


* Page 49: la déliberation joue un grand role dans l'atteinte d'un but.
La force argumentaire permet de prendre une décision éclairée. Exemple de la guerre froide.

* Page 51: les études qualitatives ont beaucoup de mérite car elles abordent les subtilités du modèle délibératif.
Cependant, certains savants peuvent ne pas être convaincus par de telles études qualitatives. Dont, Voigt (2001 : 17), un économiste qui s'intéresse à la politique délibérative,déclare que «les données qualitatives [sur la qualité du discours] ne convaincront pas les économistes. Il préférerait des analyses quantitatives plutôt que qualitatives. 

* Page 18: La recherche examinée ici sonne une mise en garde concernant la délibération.
Quand les groupes s'engagent dans des discussions, nous ne pouvons pas compter sur eux pour diminuer l’intérêt personnel étroit, offrir des chances égales de participation et d'influence même aux impuissants, pour aborder la discussion avec un esprit ouvert, et ne pas être influencé par les pressions sociales, des engagements irréfléchis aux identités sociales, ou au pouvoir, mais par l'échange de raisons pertinentes et solides.

* Plusieurs volets différents de la recherche sur le développement cognitif indique que non seulement certains, mais peut-être la plupart des gens n'ont pas la capacité requise de raison.
A défaut de bien considérer le point de vue de l'auditeur, la plupart des gens ne présentent pas leur point de vue de manière suffisamment élaborée pour que d'autres puisent les 
comprendre pleinement.

*Dans l’ensemble, l’occasion de discuter de l’argument n’est pas considéré comme un exercice de coopération conduisant à un avantage mutuel, mais il est plutôt compris comme un jeu à somme nulle qui se termine, et certains des participants gagnent et les autres perdent.

* Ces mises en garde sont certainement empiriquement correctes, mais elles soulignent que les théoriciens délibératifs ne s'attendent pas en réalité à trouver le type idéal de délibération.

* Pour étudier la politique empiriquement délibérative, l'idéal type de délibération doit être considéré comme le point final d'un continuum qui n'est jamais complètement atteint. La question empirique est alors de savoir à quelle distance les débats politiques sont du type idéal de délibération. Comme Dryzek (1990 : 87)


=== file:///C:/Users/balim/Downloads/MercierSperberWhydohumansreason.pdf[Why do humans reason? Arguments for an argumentative theory]

* Page 60: Si une personne de confiance nous dit quelque chose d'incohérentavec nos croyances précédentes, une révision est inévitable: Nous devons réviser notre confiance dans la source ou nos croyances précédentes. 

* Nous choisirons probablement la révision qui rétablit la cohérence au moindre coût, et cela consistera souvent à accepter les informations communiquées et révisant nos croyances.

* Quelles sont les options d'un communicateur voulant communiquer une information que le destinataire est peu susceptible d'accepter en toute confiance? 
Une option peut être pour le communicateur de fournir des preuves de sa fiabilité dansl'affaire en question (par exemple, si les informations sont sur les questions de santé, elle pourrait informer le destinataire queelle est médecin).  

* Page 61: plusieurs prédictions peuvent être tirées de l'argumentation de la théorie du raisonnement.

* Le premier et le plus simple est que le raisonnement devrait bien faire ce pour quoi il a évolué: produire et évaluer des arguments (sect. 2.1 et 2.2). 
En général, les adaptations fonctionnent mieux lorsqu'elles sont utilisées pour exécuter la tâche pour laquelle ils ont évolué. En conséquence,le raisonnement devrait produire ses meilleurs résultats dans les contextes argumentatifs, notamment dans les discussions de groupe(sect. 2.3).

* Quand on veut convaincre un interlocuteur avec un point de vue différent, nous devrions chercher des arguments en faveur de notre point de vue plutôt qu'en faveur du sien.
Par conséquent, la prochaine prédiction est que le raisonnement utilisé pour produire un argument devrait montrer une forte confirmation de biais (sect. 3). 

* Une autre prédiction connexe est que, lorsque les gens raisonnent par eux-mêmes sur l'une de leurs opinions, ils sont susceptibles de le faire de manière proactive, c'est-à-dire dans un contexte dialogique, et surtout pour trouver des arguments qui soutiennent leur opinion. 

* NB: Enfin, nous veulons explorer la possibilité que, même dans la prise de décision, la fonction principale du raisonnement est de produire pour convaincre les autres plutôt que de trouver la meilleure décision. Ainsi, nous prédisons que le raisonnement conduira les gens vers des décisions pour lesquelles ils peuvent argumenter -décisions qu'ils peuvent justifier - même si ces décisionsne sont pas optimales (sect. 5)
