== Résumé du livre sur le végétarisme et le changement  de comportement aliments des personnes

* Dans le chapitre 13 ‘Média sans viande’, l’auteur évoque la force des médias (télévisions, livres, internet, vidéos, journaux…) à pouvoir influer le comportement et les croyances des personnes notamment sur le fait de devenir végetarien.

* En effet, Une étude sur les végétariens - menée des années avant Facebook ou YouTube  a constaté que près d'un tiers de personnes avaient changé
leur alimentation à la suite d'une certaine forme de média (MacNair 1998). Une étude 2012 aux États-Unis,
a montré que ce nombre était passé à 43% (Haverstock et
Forgays 2012). 

* Alors, quel impact les médias peuvent-ils avoir? 

* Les livres

* The Omnivore's Dilemma de Michael Pollan, un livre publié en 2006. Ce livre expose les conséquences de l’agriculture-élévage extensifs.
Paul ROZIN voulait savoir quel impact la lecture de ce livre pourrait avoir sur l’attitude et comportements des personnes. À l'automne 2007, il impose la lecture de Omnivore's Dilemma à toute la classe de première année
à l'Université de Pennsylvanie (pour leur orrientation). Rozin a interrogé des étudiants avant,
immédiatement après, et un an après avoir lu le livre pour voir ce que
effet que cela a eu sur leurs attitudes à l'égard de la nourriture.
Comparés aux étudiants de première année qui n'avaient pas lu le livre, les étudiants
étaient plus réticents à manger de la viande, plus intéressés à manger des aliments biologiques,
et plus susceptibles de penser que la qualité de l'approvisionnement alimentaire américain était en baisse.
Ils étaient également plus favorables au mouvement environnemental et plus
opposé aux subventions gouvernementales au maïs. 
Un an plus tard, cependant, plusieurs de ces attitudes, dont
réticence à manger de la viande - avait disparu. Les seules préoccupations qui subsistent
sur les subventions au maïs, la qualité de l’approvisionnement alimentaire et le soutien
mouvement environnemental
les gens changent difficilement LEUR COMPORTEMENT ALIMENTAIRE

Les Simpsons
Le dessin animé The Simpsons court depuis plus de
vingt-cinq ans aux États-Unis. Lisa Simpson est probablement la végétarienne de dessin animé la plus célèbre au monde.
Une étude a cherché à savoir si les filles qui regardaient Lisa devenir végétarienne
serait inspiré à faire de même. En laboratoire, l'épisode a été
montré à des filles de neuf et dix ans qui ne l'avaient pas déjà vu. Ils
on leur a ensuite demandé ce qu'ils pensaient de devenir végétarien.
Après avoir regardé l'épisode, environ 10 % des filles avaient intention de devenir végétarienne, cependant ce nombre est tombé à 5% quelques semaines après. 

Malheureusement, l'étude n'a pas vérifié si les filles avaient réellement changé
leurs régimes. Mais cela a suggéré que même un personnage de dessin animé peut inspirer
les gens veulent abandonner la viande, mais l’application ou la constance de la résolution en sont tout autre.

Vidéos en ligne
En 2011, la Humane League a mené des enquêtes de suivi auprès de
des adolescents qui avaient vu une vidéo sur la cruauté envers les animaux de ferme quelques mois plus tôt.
Ils n'ont pu interroger que ceux qui avaient «aimé» la vidéo via Facebook,
près d'un tiers d'entre eux ont déclaré avoir éliminé le poulet et la viande rouge de
leur alimentation. Un autre tiers a déclaré avoir réduit le poulet et la viande rouge. Moitié
des répondants ont déclaré que la vidéo les avait amenés à couper ou à réduire le poisson, les œufs,
et les produits laitiers (The Humane League).
Ces deux études sont probablement également remplies de surdéclarations. Plus
les gens qui ont dit avoir réduit leur viande ou qui avaient l'intention de le faire, probablement
n'a pas fait de changement. Pourtant, les enquêtes témoignent de la puissance d'un
outil vidéo en ligne est, en particulier lorsqu'il est destiné aux jeunes. Avec
des millions d'adolescents regardent chacun des vidéos en ligne sur l'agriculture industrielle
année, il n'est pas étonnant que le nombre de végétariens, végétaliens et réducteurs de viande
grimpe!
