== Résumé du livre sur le végétarisme et le changement  de comportement alimentaire  des personnes

* Dans le chapitre 13 ‘Média sans viande’, l’auteur évoque la force des médias (télévisions, livres, internet, vidéos, journaux…) à pouvoir influer le comportement et les croyances des personnes notamment sur le fait de devenir végetarien.

* En effet, Une étude sur les végétariens - menée des années avant Facebook ou YouTube  a constaté que près d'un tier de personnes avait changé leur alimentation après exposition de média quelconque (MacNair 1998). Une étude 2012 aux États-Unis,
a montré que ce nombre était passé à 43% (Haverstock et Forgays 2012). 

* Alors, quel impact les médias peuvent-ils avoir? 

== Les livres

* The Omnivore's Dilemma de Michael Pollan, un livre publié en 2006. Ce livre expose les conséquences de l’agriculture-élévage intensifs.

* Paul ROZIN voulait savoir quel impact la lecture de ce livre pourrait avoir sur l’attitude et comportements des personnes. À l'automne 2007, il impose la lecture de Omnivore's Dilemma à toute la classe de première année
à l'Université de Pennsylvanie (pour leur orrientation).

** Rozin a interrogé des étudiants avant,
immédiatement après, et un an après avoir lu le livre pour voir ce que
effet que cela a eu sur leurs attitudes à l'égard de la nourriture.

** Comparés aux étudiants de première année qui n'avaient pas lu le livre, les étudiants
étaient plus réticents à manger de la viande, plus intéressés à manger des aliments bio,
et plus à meme de penser que la qualité de l'approvisionnement alimentaire américain était en baisse.
Ils étaient également plus favorables au mouvement environnemental et plus
opposé aux subventions gouvernementales au maïs. 

** Un an plus tard, cependant plusieurs de ces attitudes, dont la réticence à manger de la viande avait disparu. 
Les seules préoccupations qui subsistaient étaient:  les subventions au maïs, la qualité de l’approvisionnement alimentaire et le soutien environnemental à la subvention du maïs.

** En conclusion de cette étue, nous retiendront que soumis à deles gens changent difficilement LEUR COMPORTEMENT ALIMENTAIRE.

== Les Simpsons

* Le dessin animé The Simpsons court depuis plus de vingt-cinq ans aux États-Unis.
Lisa Simpson est probablement la végétarienne de dessin animé la plus célèbre au monde.

* Une étude a cherché à savoir si les filles qui regardaient Lisa devenir végétarienne
seraient inspiré à faire de même. 

* En laboratoire, l'épisode a été montré à des filles de neuf à dix ans qui ne l'avaient pas déjà vu.

* On leur a ensuite demandé ce qu'ils pensaient devenir végétariennes.

* Après avoir regardé l'épisode, environ 10 % des filles avaient intention de devenir végétarienne, cependant ce nombre est tombé à 5% quelques semaines après. 

* Malheureusement, l'étude n'a pas vérifiée si les filles avaient réellement changé
leurs régimes. 

* Conclusion, cela suggére que même un personnage de dessin animé peut inspirer
les gens à vouloir abandonner la viande, mais l’application ou la constance de la résolution en sont tout autre.

** En effet, dès l'exposition au média, les personnes souhaitent changer de comportement, paasent le plus souvent à l'acte, mais reviennent majoritairement à leur habitude avant l'exposition aux médias. Le comportement alimentaire notamment le mode d'alimentation est un phénoméne très complexe qui allie cognition (restriction), compétence, connaissances, environnement (niveau macro et micro), disponibilité et accessibilité des produits alimentaires (dans notre cas, la viande et autres produits d'origine animal).

** Dans notre dispositif, les personnes après s'etre formé un jugement délibére, retourneront à leur position de départ

== Vidéos en ligne

* En 2011, la Humane League a mené des enquêtes de suivi auprès de
des adolescents qui avaient vu une vidéo sur la cruauté envers les animaux de ferme quelques mois plus tôt.

* Ils n'ont pu interroger que ceux qui avaient «aimé» la vidéo via Facebook:  

** près d'un tiers d'entre eux ont déclaré avoir éliminé le poulet et la viande rouge de
leur alimentation.

** Un autre tiers a déclaré avoir réduit le poulet et la viande rouge. 

** La moitié des répondants a déclaré que la vidéo les avait amenés à couper ou à réduire le poisson, les œufs,
et les produits laitiers (The Humane League).

Cette étude est probablement remplie de surdéclaration. 

** La majorité les gens qui ont dit avoir réduit leur consommation viande ou qui avaient l'intention de le faire, n'a pas fait de changement. 
